### ISSUE TITLE
Which Plugin is used for syntax/ blankspace error detection?

### ISSUE THREAD

**Issue by knight-byte** [siduck76/neovim-dotfiles#24]
### About the Issue:
Which plugin is used for syntax/blankspace error detection. 

![image](https://user-images.githubusercontent.com/54370855/113854596-a999b200-97bc-11eb-918e-9c2d2b409ab9.png)

The above Screenshot  is an example of Python code. Its too annoying error highlights in the middle of the code. and doesnt refresh after the modification/fixing the error

#### After fixing the error and saving it 
![image](https://user-images.githubusercontent.com/54370855/113855347-8b808180-97bd-11eb-8827-d1d9453acada.png)

After fixing the error the higlighted message doesnt go. i have to quit nvim and open again.

### System Details:
OS   :  Arch Linux
WM  :  Xmonad

---
BTW great config 👍🏻

**Comment by siduck76** [comment]
@knight-byte is that pyls?

**Comment by knight-byte** [comment]
ok let me check this method.
there is one great plugin [ale](https://github.com/dense-analysis/ale) for syntax highlight and error detection 
and stuff

**Comment by knight-byte** [comment]
Tried with pyright still the same issue

![image](https://user-images.githubusercontent.com/54370855/113860864-25e3c380-97c4-11eb-8343-f9869c200206.png)

**Comment by siduck76** [comment]
can you show me your lspconfig?

**Comment by knight-byte** [comment]
heres my [lspconfig](https://del.dog/rocyqarebu.txt)

**Comment by marvelman3284** [comment]
Using pyls works fine for me. 
Error:
![image](https://user-images.githubusercontent.com/58921302/113862735-d034fa00-9776-11eb-9535-5129e784eb95.png)
Fixing the error:
![image](https://user-images.githubusercontent.com/58921302/113862852-f0fd4f80-9776-11eb-9531-17bc858400bd.png)
Exiting out of `insert` mode to autosave the document:
![image](https://user-images.githubusercontent.com/58921302/113862931-07a3a680-9777-11eb-8abd-a77ab80a1253.png)

As for your error, try manually saving by typing `:w` while in normal mode to see if the syntax errors go away.

**Comment by knight-byte** [comment]
https://user-images.githubusercontent.com/54370855/113865811-2aab7600-97ca-11eb-9d42-6e0919197d77.mp4

This is the referance video of issue i was mentioning above ( using pyly ). I manually saved many time but didnt work. on saving and quiting the error refreshes

**Comment by siduck76** [comment]
is the issue same with pyright? @knight-byte

**Comment by knight-byte** [comment]
yes same issue with pyright ... i have removed the the complete python lint packages to ignore all sort of popup error in the middle of code... i future i may use ALE plugin for that which support all language which i use in my current config [**LINK**](https://github.com/knight-byte/Vim-Configuration) which is not the best but works perfect for me

**Comment by siduck76** [comment]
use jedi lsp , it will work I think @knight-byte

**Comment by laughing-stock** [comment]
>  simplescreenrecorder-2021-04-07_17.52.28.mp4 
> This is the reference video of issue i was mentioning above ( using pyls ). I have manually saved many time but didnt work. on saving and quiting the error refreshes

Hey, try pyright latest version.(by building it on your pc)
The issues will be fixed.

**Comment by marvelman3284** [comment]
@knight-byte Its been a few days since you've mentioned any issues so is it safe to assume that you fixed the issue? If you did could you just leave one final comment detailing how you fixed it in case other people have this issue.

**Comment by knight-byte** [comment]
No i didnt find any solution for that. I have disable the all kind of linting to avoid all kind of error highlighting in the middle of code.

**Comment by siduck76** [comment]
@knight-byte  did you try jedi lsp?

**Comment by knight-byte** [comment]
Tried jedi but same issue

currently using [ALE plugin](https://github.com/dense-analysis/ale) 
- Error indicated on the number : 
![image](https://user-images.githubusercontent.com/54370855/114659807-df392080-9d11-11eb-8abd-9d1eb8cef538.png)
- On going to that line full description shows up : 
![image](https://user-images.githubusercontent.com/54370855/114659887-ff68df80-9d11-11eb-8499-46522d00173e.png)
- After modification and saving it ...it updates : 
![image](https://user-images.githubusercontent.com/54370855/114660299-b2d1d400-9d12-11eb-8b15-4cb47cd0b27a.png)
This works perfectly for me

**Comment by siduck76** [comment]
@knight-byte  lspconfig has been updated  , could you check again?  update your configs.

**Comment by siduck76** [comment]
@mTvare6 does this issue happen with you?
