### ISSUE TITLE
Incorrect auto completion in JS

### ISSUE THREAD

**Issue by real-marshal** [siduck76/neovim-dotfiles#28]
Hey, awesome config but I have a problem with auto completion in JS files. It completely ignores the context and suggests the same regardless of the code before. E.g. I enter `axios.` (which is a lib in TS) and instead of showing all the methods of its instance I get completely unrelated stuff like every variable/function of the current file, some globals etc. It's not supposed to be this way, right?

**Comment by siduck76** [comment]
@real-marshal Is the Lsp server even running? check :LspInfo.

**Comment by real-marshal** [comment]
@siduck76 yep, it says tsserver is active and attached to the buffer

**Comment by siduck76** [comment]
@real-marshal  I think this issue should be reported here https://github.com/neovim/nvim-lspconfig/

**Comment by siduck76** [comment]
@real-marshal can you try this config? 

local lspconf = require "lspconfig"

lspconf.tsserver.setup {
    root_dir = function()
        return vim.loop.cwd()
    end
}

**Comment by real-marshal** [comment]
@siduck76 I created a new project, did `git init` and `npm init`, but autocomplete still shows everything possible instead of correct suggestions. 

> ac6afa3 should fix it I think

That commit was made 6 days ago, I already have it in my install.sh. Maybe you meant this one f71984e ?

**Comment by siduck76** [comment]
@real-marshal This might fix it , https://github.com/siduck76/neovim-dots/commit/ebff217665b989ee26997e2adb7bce50580942bb

**Comment by real-marshal** [comment]
@siduck76 nah, it's the same. But I seem to find the actual problem. When I enter `console.`, then save & close the file and open it again it shows `Identifier expected` error and autocomplete after that dot correctly shows all console methods. The error though remains. Now when I enter `.` anywhere in a file I get console methods instead of global things. So it seems like LSP runs only one time when I open the file and after that it doesn't see any changes / doesn't check the file. Idk maybe it's a bug with nvim-lspconfig, looked at the issues there but didn't find anything similar.

**Comment by siduck76** [comment]
> @siduck76 I think it would be better if you file this issue at their repo or official or https://github.com/theia-ide/typescript-language-server .

**Comment by siduck76** [comment]
@real-marshal I think it would be better if you file this issue at their repo or official or https://github.com/theia-ide/typescript-language-server .

**Comment by siduck76** [comment]
> @real-marshal I think it would be better if you file this issue at the nvimlspconfig repo or https://github.com/theia-ide/typescript-language-server.

**Comment by siduck76** [comment]
@real-marshal have you installed axios from npm?

**Comment by siduck76** [comment]
@Vanderscycle do you have this issue?

**Comment by Vanderscycle** [comment]
@siduck76 you can assign me to this issue. I'll investigate.

**Comment by Vanderscycle** [comment]
Axios works fine in JS files but auto completion is not present in TS. We can close this issue, but I'll raise an issue in TS LSP. I'm still fairly new to TS and JS so I don't have much experience with both languages anf their quirks.

![axios](https://user-images.githubusercontent.com/52706578/118136661-34bc2800-b3b9-11eb-8916-ed5a56214106.png)

**Comment by siduck76** [comment]
I think yes , my friend tested it too and it works for him 

![image](https://user-images.githubusercontent.com/59060246/118141659-36bcd000-b427-11eb-85f2-5b70cb9eb1ce.png)

@real-marshal Seems like you need to install the axios lib on your system , I'll close this issue for now and re-open it if you want.
