### ISSUE TITLE
Sumneko path and bin

### ISSUE THREAD

**Issue by Vanderscycle** [siduck76/neovim-dotfiles#43]
Hi,

What is the purpose of sumneko bin and path? On my config, I do not have files created at sumneko specific path and :Healthcheck returns an error. Do I need to create the folders during install? 

![sumneko](https://user-images.githubusercontent.com/52706578/117580694-ff0ffa00-b0ad-11eb-8214-96979d48598d.png)
Sumneko in lsp config
![sumneko2](https://user-images.githubusercontent.com/52706578/117580709-1b139b80-b0ae-11eb-818f-7e52b1ecf293.png)

**Comment by siduck76** [comment]
Hi , Sorry I forgot to mention the sumneko part in the readme  , you just have to build the sumneko lua lsp and put its folder in ~/.config 
 
cd ~/.config
git clone https://github.com/sumneko/lua-language-server
cd lua-language-server
git submodule update --init --recursive

cd 3rd/luamake
ninja -f ninja/linux.ninja
cd ../..
./3rd/luamake/luamake rebuild

**Comment by Vanderscycle** [comment]
I'm able to do everything except luamake rebuild.
I'll make a pr to add the commands to the manual install in the README.md and change the install.sh once I get this working.

**Comment by siduck76** [comment]
Thanks! I'm not familiar with shell scripting , It'd be really appreciable if the install.sh script gets cleaned up, or we could remove the current install.sh since it doesnt work for mac/windows. We could have a fresh start with the install script . Making it work on linux would be enough for now , then slowly adding support for  other OS's.

**Comment by Vanderscycle** [comment]
That could be a good enhancement, and I can definitely take a look to see if I can refactor install.sh for Linux. MacOs would be second as the process is quite close to Linux. No idea for Windows lol :sweat_smile:

**Comment by Vanderscycle** [comment]
Sumneko, last update fixed the issue for me.
