### ISSUE TITLE
(improvement) A more responsive zen-mode plugin alternative

### ISSUE THREAD

**Issue by Vanderscycle** [siduck76/neovim-dotfiles#48]
@siduck76,

Try this plugin from [folke](https://github.com/folke/zen-mode.nvim), its a zen mode plugin that, with neovim newest update, works better than [kdav5758](https://github.com/kdav5758/TrueZen.nvim) current version as it opens a new window and makes it easier to get in and out.

**Comment by siduck76** [comment]
@Vanderscycle  I think we are already ok with Truezin.nvim , btw can you tell the new features folke's plugin provides than Truezen.nvim?

**Comment by siduck76** [comment]
I like the focus feature in Truezen.nvim

https://user-images.githubusercontent.com/59060246/118587763-c7463800-b7ba-11eb-92e9-c24469921cb2.mp4

tab 1(bufferline) : before tzfocus ( has multiple split windows)

tab 2 : shows only focused window (done by tzfocus) , even if I close this focused window it will not close its original window opened from tab 1

**Comment by Vanderscycle** [comment]
Didn't know about the focus mode. All I tried was the ataraxis mode and the minimalist mode which I always found awkward to set up since you could only have one window while Folke's zen allow you to switch tabs while in zenMode.

I'll give focus mode another try.

**Comment by siduck76** [comment]
yeah if you want any feature on Truezen.nvim or have any issues then let me know , Truezen.nvim's creator my friend and he'd help for sure :p

**Comment by kdav5758** [comment]
> Folke's zen allow you to switch tabs while in zenMode.

Are you sure you can't do that with TrueZen?

https://user-images.githubusercontent.com/58336662/118657866-78e06b80-b7b1-11eb-8c27-7d37d8416171.mp4


> All I tried was the ataraxis mode and the minimalist mode which I always found awkward to set up

Sorry if there is a bunch of stuff to setup. All I wanted was to give users complete control over the plugin's functionalities :)

> Didn't know about the focus mode.

And it has two different sub-modes too lol (use the `experimental` one, it's the I personally recommend and use)
